import React from 'react';

export const TEMPLATE_MAP = {
  'dr-1': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.DoctorD1 }))),
  'dr-2': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.DoctorD2 }))),
  'dr-3': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.DoctorD3 }))),
  'dr-4': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.DoctorD4 }))),
  'dr-5': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.DoctorD5 }))),
  'ns-1': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.NurseN1 }))),
  'ns-2': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.NurseN2 }))),
  'ns-3': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.NurseN3 }))),
  'ns-4': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.NurseN4 }))),
  'ns-5': React.lazy(() => import('../components/Templates/MedicalTemplates').then(m => ({ default: m.NurseN5 }))),
  'lw-1': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.LawyerL1 }))),
  'lw-2': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.LawyerL2 }))),
  'lw-3': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.LawyerL3 }))),
  'lw-4': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.LawyerL4 }))),
  'lw-5': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.LawyerL5 }))),
  'tc-1': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.TeacherT1 }))),
  'tc-2': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.TeacherT2 }))),
  'tc-3': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.TeacherT3 }))),
  'tc-4': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.TeacherT4 }))),
  'tc-5': React.lazy(() => import('../components/Templates/LegalAndEduTemplates').then(m => ({ default: m.TeacherT5 }))),
  'mk-1': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.MarketingM1 }))),
  'mk-2': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.MarketingM2 }))),
  'mk-3': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.MarketingM3 }))),
  'mk-4': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.MarketingM4 }))),
  'mk-5': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.MarketingM5 }))),
  'ds-1': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.DesignerDS1 }))),
  'ds-2': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.DesignerDS2 }))),
  'ds-3': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.DesignerDS3 }))),
  'ds-4': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.DesignerDS4 }))),
  'ds-5': React.lazy(() => import('../components/Templates/CreativeTemplates').then(m => ({ default: m.DesignerDS5 }))),
  'mk-6': React.lazy(() => import('../components/Templates/AccountingBlueTemplate')),
  'mk-7': React.lazy(() => import('../components/Templates/SageSidebarTemplate')),
  'mk-8': React.lazy(() => import('../components/Templates/CorporateNavyDynamicTemplate')),
  'ds-6': React.lazy(() => import('../components/Templates/TimelineArtisticTemplate')),
  'ds-7': React.lazy(() => import('../components/Templates/StructuredGrayModernTemplate')),
  'ats-1': React.lazy(() => import('../components/Templates/ProfessionalTemplate')),
  'ats-2': React.lazy(() => import('../components/Templates/TechTemplate')),
  'ats-3': React.lazy(() => import('../components/Templates/MinimalistTemplate')),
  'ats-4': React.lazy(() => import('../components/Templates/ModernTemplate')),
  'ats-5': React.lazy(() => import('../components/Templates/FormalTemplate')),
  'ats-6': React.lazy(() => import('../components/Templates/ATSGoldEliteTemplate')),
  'rt-1': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.RetailR1 }))),
  'rt-2': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.RetailR2 }))),
  'rt-3': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.RetailR3 }))),
  'rt-4': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.RetailR4 }))),
  'rt-5': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.RetailR5 }))),
  'fr-1': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.FresherF1 }))),
  'fr-2': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.FresherF2 }))),
  'fr-3': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.FresherF3 }))),
  'fr-4': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.FresherF4 }))),
  'fr-5': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.FresherF5 }))),
  'st-1': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.StudentS1 }))),
  'st-2': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.StudentS2 }))),
  'st-3': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.StudentS3 }))),
  'st-4': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.StudentS4 }))),
  'st-5': React.lazy(() => import('../components/Templates/ServiceAndEntryTemplates').then(m => ({ default: m.StudentS5 }))),
};
